# Generated by Django 2.2.6 on 2019-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('local', models.CharField(max_length=100, verbose_name='Setor - Bloco - Sala')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['title'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.RemoveField(
            model_name='link',
            name='email',
        ),
        migrations.RemoveField(
            model_name='link',
            name='local',
        ),
        migrations.RemoveField(
            model_name='link',
            name='phone',
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=500, null=True, verbose_name='Link'),
        ),
    ]
