# Generated by Django 2.2.6 on 2019-11-04 14:14

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191104_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=faicon.fields.FAIconField(max_length=50, null=True, verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='icon',
            field=faicon.fields.FAIconField(max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
