# Generated by Django 2.2.6 on 2019-12-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191104_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['name'], 'verbose_name': 'Banner', 'verbose_name_plural': '#01: Banners'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['title'], 'verbose_name': 'Contato', 'verbose_name_plural': '#07: Contatos'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Informação do Curso', 'verbose_name_plural': '#02: Informações do Curso'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['title'], 'verbose_name': 'Informação da Disciplina', 'verbose_name_plural': '#04: Informações da Disciplina'},
        ),
        migrations.AlterModelOptions(
            name='infos',
            options={'ordering': ['title'], 'verbose_name': 'Descrição', 'verbose_name_plural': '#08: Descrição da Disciplina'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['title'], 'verbose_name': 'Link', 'verbose_name_plural': '#06: Links'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['name'], 'verbose_name': 'Corpo Docente', 'verbose_name_plural': '#03: Docentes'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['title'], 'verbose_name': 'Referência', 'verbose_name_plural': '#09: Referências'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['title'], 'verbose_name': 'Template', 'verbose_name_plural': '#05: Templates'},
        ),
    ]
