# Generated by Django 2.2.6 on 2019-12-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191219_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(upload_to='course/images', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='icon',
            field=models.ImageField(upload_to='discipline/images', verbose_name='Ícone'),
        ),
    ]
