# Generated by Django 2.2.6 on 2019-12-29 19:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191219_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição da Disciplina'),
        ),
    ]
