# Generated by Django 2.2.6 on 2019-12-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191229_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
